/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stmf411re.h"
#include "stmf411re_diver_GPIO.h"



int main(void)
{


	GPIO_PerClkConstrol(GPIOA, ENABLE);
	GPIO_Handle_t led;

	led.pGPIOx=GPIOA;
	led.pcnfgGPIOx.GPIO_PinMode=GPIO_MODE_OUT;
	led.pcnfgGPIOx.GPIO_PinNumber=5;
	led.pcnfgGPIOx.GPIO_PinOPType=GPIO_OUT_TYPE_PP;
	led.pcnfgGPIOx.GPIO_PinPuPdControl=GPIO_NO_PU_PD;
	led.pcnfgGPIOx.GPIO_PinSpeed=GPIO_OUT_SPEED_HIGH;
	GPIO_Init(&led);

	GPIO_Handle_t button;
	GPIO_PerClkConstrol(GPIOC, ENABLE);
	button.pGPIOx=GPIOC;
	button.pcnfgGPIOx.GPIO_PinMode=GPIO_MODE_IT_FT;
	button.pcnfgGPIOx.GPIO_PinNumber=13;
	button.pcnfgGPIOx.GPIO_PinOPType=GPIO_OUT_TYPE_PP;
	button.pcnfgGPIOx.GPIO_PinPuPdControl=GPIO_PU;
	button.pcnfgGPIOx.GPIO_PinSpeed=GPIO_OUT_SPEED_HIGH;
	GPIO_Init(&button);

//	GPIO_WriteToOutputPin(GPIOA, 5, 1);
	GPIO_IRQITConfig(40, ENABLE);


//	GPIO_Init(pGPIOHandle);
//	GPIO_PerClkConstrol(GPIOA, ENABLE);
    /* Loop forever */
	for(;;);

}




void EXTI15_10_IRQHandler(void)
{
	GPIO_IRQHandling(13);
	GPIO_ToggleOutputPin(GPIOA, 5);
}
